services:
  web:
    build: .
    container_name: splikami_app
    env_file: .env
    volumes:
      - ./database:/app/database
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: splikami_nginx
    depends_on:
      - web 
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot_challenges:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    restart: always