[phases.setup]
nixPkgs = [
    "python312",
    "gcc",
    "pkg-config",
    "zlib",
    "tesseract",
    "tesseract-data-eng",
    "tesseract-data-nld",
    "tesseract-data-spa",
    "tesseract-data-por",
    "tesseract-data-fra"
]
aptPkgs = [
    "python3.12-dev",
    "build-essential",
    "libpq-dev",
    "curl",
    "wget",
    "libtesseract-dev"
]

[phases.install]
cmds = [
    "python3.12 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install wheel setuptools",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = [
    ". /opt/venv/bin/activate",
    "python manage.py migrate",
    "python manage.py collectstatic --noinput"
]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn SplikamiProject.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120"

[variables]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"
PATH = "/opt/venv/bin:$PATH"
LANG = "C.UTF-8"
LC_ALL = "C.UTF-8"
