# Generated by Django 5.0.7 on 2024-09-03 09:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='naam van bijvoorbeeld een krant: Extra', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='afbeelding te zien in de collectie overzicht', null=True, upload_to='collection_thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('location', models.CharField(help_text='exacte locatie of Online', max_length=255)),
                ('url', models.URLField(blank=True, help_text='Url naar de online call indien het event online is', null=True)),
                ('image', models.ImageField(blank=True, help_text='afbeelding voor het event', null=True, upload_to='events/')),
                ('pdf', models.FileField(blank=True, help_text='PDF met event details', null=True, upload_to='events/')),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pdf', models.FileField(blank=True, help_text='Pdf van de cursus, laat dit veld leeg als de cursus op een externe website staat.', null=True, upload_to='courses/')),
                ('link', models.URLField(blank=True, help_text='link naar de externe cursus', null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('students', models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Vul dit in indien je een los document toevoegd. Als dit document onderdeel van een collectie is kun je dit veld leeglaten: de titel word automatisch bepaald.', max_length=255, null=True)),
                ('date_added', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('publish_date', models.DateField(blank=True, db_index=True, help_text='datum van uitgave, publicatie datum', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='document_thumbnails/')),
                ('page_count', models.IntegerField(default=0)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='SplikamiApp.collection')),
                ('rubric', models.ManyToManyField(blank=True, related_name='documents', to='SplikamiApp.rubric')),
                ('subject', models.ManyToManyField(blank=True, related_name='documents', to='SplikamiApp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=10000, null=True)),
                ('image', models.ImageField(upload_to='pages/')),
                ('thumbnail', models.ImageField(upload_to='page_thumbnails/')),
                ('page_number', models.IntegerField(db_index=True, default=1)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='SplikamiApp.document')),
            ],
        ),
    ]
